import { Inter } from "next/font/google";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import { LoadingProvider } from "@/context/LoadingContext";
import "./globals.css";
import Layout from "./components/layout";
import { Providers } from "@/reducer/providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <LoadingProvider>
            <Layout>
              <ToastContainer />
              {children}
            </Layout>
          </LoadingProvider>
        </Providers>
      </body>
    </html>
  );
}
